name: Tests

on:
  push:
  workflow_dispatch:

jobs:
  tests:
    name: Integration and Unit tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_TOKEN }}
      - name: Setup Go 1.15.15
        uses: actions/setup-go@v2
        with:
          go-version: 1.15.15
      - name: Build and run tests for Go 1.15.15
        run:
          ./scripts/run-tests.sh -mod=mod
      - name: Setup Go 1.16.12
        uses: actions/setup-go@v2
        with:
          go-version: '1.16.12'
      - name: Build and run tests for Go 1.16.12
        run: |
          ./scripts/run-tests.sh -mod=mod
      - name: Setup Go 1.17.5
        uses: actions/setup-go@v2
        with:
          go-version: '1.17.5'
      - name: Build and run tests for Go 1.17.5
        run: |
          ./scripts/run-tests.sh -mod=mod
      - name: "Setup Go 'master'"
        uses: actions/setup-go@v2
        with:
          go-version: 'master'
      - name: "Build and run tests for Go 'master'"
        run: |
          ./scripts/run-tests.sh -mod=mod
      - name: "Setup Go 'tip'"
        uses: actions/setup-go@v2
        with:
          go-version: 'tip'
      - name: "Build and run tests for Go 'tip'"
        run: |
          ./scripts/run-tests.sh -mod=mod
  acceptance:
    name: Acceptance tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v2
      - name: Checkout mock-server action
        uses: actions/checkout@v2
        with:
          repository: pubnub/client-engineering-deployment-tools
          ref: github-actions
          token: ${{ secrets.GH_TOKEN }}
          path: deployment-tools
      - name: Run mock server action
        uses: ./deployment-tools/actions/mock-server
        with:
          token: ${{ secrets.GH_TOKEN }}
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Run acceptance tests (optional)
        run: |
          cd tests/contract
          go test -path ../../sdk-specifications/features -tagsFilter "~@skip && ~@na=go && @beta" -format "junit:beta.xml"
        continue-on-error: true
      - name: Run acceptance tests (required)
        run: |
          cd tests/contract
          go test -path ../../sdk-specifications/features -tagsFilter "~@skip && ~@na=go && ~@beta" -format "junit:main.xml"
      - name: Expose acceptance tests reports
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: acceptance-test-reports
          path: |
            ./tests/contract/beta.xml
            ./tests/contract/main.xml
          retention-days: 7
